- 
  name: Copy file to target servers
  hosts: all
  tasks:
    - name: copy file
      copy: 
        src: /root/test-project/devops_new
        dest: /home/
        owner: root
        group: root
        mode: '0644'
        
